// Framework-agnostic grid logic: sorting, filtering, paging will live here so it stays testable without a DOM.
export type {
  CellTemplateContext,
  ColumnDefinition,
  FieldPath,
  CellSelectEvent,
  CellSelectionChangeEvent,
  CellSelectionMode,
  CellSelectionState,
  ColumnAlignment,
  ColumnConstraints,
  ColumnOrderEvent,
  ColumnOrderState,
  ColumnResizeEvent,
  ColumnResizeSession,
  ColumnResolveOptions,
  ColumnSelectEvent,
  ColumnSelectionChangeEvent,
  ColumnSizeDefaults,
  ColumnSizingState,
  ColumnSortEntry,
  ColumnSortEvent,
  ColumnSortState,
  ColumnsSelectEvent,
  ColumnType,
  ColumnWrapConfig,
  DisplayRow,
  DropSide,
  FilterEntry,
  FilterPredicate,
  FilterState,
  GroupByEntry,
  GroupByEvent,
  GroupByState,
  GroupExpansionEvent,
  GroupExpansionState,
  GroupFilterEntry,
  PaginationChangeEvent,
  PaginationState,
  PredicateFilterEntry,
  ResolvedColumn,
  ResolvedGroupRow,
  ResolvedRow,
  RowSelectEvent,
  RowSelectionChangeEvent,
  RowsSelectEvent,
  SelectableConfig,
  SelectedCell,
  SelectedCellRef,
  SelectedColumn,
  SelectIntent,
  SelectionDiff,
  SelectionMode,
  SelectionState,
  SortDirection,
  TextFilterEntry,
  ValueFilterEntry,
} from "./types";
export type { KeyShortcutCapabilities } from "./util/grid";
export {
  accessDotted,
  alignmentForType,
  buildKeyShortcuts,
  defineColumnsFromRows,
  getColumnId,
  resolveColumnLabel,
  resolveRowId,
} from "./util/grid";
export type { GridFocus, NavigationModifiers } from "./util/navigation";
export { clampFocus, HEADER_ROW, nextFocusForKey } from "./util/navigation";
export {
  applyColumnOrder,
  moveColumnBefore,
  movesColumn,
  resolveDropBefore,
  resolveKeyboardDropTarget,
} from "./util/ordering";
export {
  applySelectionIntent,
  clearSelection,
  diffSelection,
  intentOf,
  isSameCell,
  selectAll,
  selectCell,
  selectOnly,
  selectRange,
  toggleCellSelection,
  toggleSelection,
} from "./util/selection";
export {
  DEFAULT_COLUMN_SIZES,
  KEYBOARD_STEP,
  applyColumnResize,
  beginColumnResize,
  clampColumnWidth,
  fitColumnsToWidth,
  resolveColumnConstraints,
  resolveColumnWidths,
  revertColumnSize,
  sizeColumnToContent,
  totalColumnWidth,
} from "./util/sizing";
export {
  compareValues,
  sortDirectionFor,
  sortPriorityFor,
  sortRows,
  toggleColumnSort,
} from "./util/sorting";
export {
  clearAllFilters,
  filterQueryFor,
  filterRows,
  matchesQuery,
  setColumnFilter,
} from "./util/filtering";
export {
  collapseAllGroups,
  expandAllGroups,
  groupRowId,
  groupRows,
  moveGroupByBefore,
  movesGroupBy,
  toggleGroupExpansion,
} from "./util/grouping";
export {
  resolveCell,
  resolveColumns,
  resolveRows,
  resolveShownRows,
} from "./util/rows";
export type { PaginatedRows } from "./util/paging";
export { paginateRows } from "./util/paging";
